SELECT *
FROM RESOURCES
WHERE NOMBRE_RESOURCE LIKE '%facebook%';


cms360.dbo.FORMATODETALLE
cms360.dbo.INFORMATION
cms360.dbo.PRODUCTOCATEGORIA
cms360.dbo.PRODUCTOTIPOLIKE
cms360.dbo.SCMENU
cms360.dbo.SCSUBMENU
cms360.dbo.USERGUSTO
cms360.dbo.SCINFORMACIONSUBMENU
cms360.dbo.USERGUSTO



