SELECT SCMENU.*, SCMENU_SCSUBMENU.*, SCSUBMENU.*
FROM SCMENU SCMENU, SCMENU_SCSUBMENU SCMENU_SCSUBMENU, SCSUBMENU SCSUBMENU
WHERE 
	SCMENU_SCSUBMENU.scmenuList_ID = SCMENU.ID
	AND SCMENU.ID = SCSUBMENU.ID
scmenuList_ID|scsubmenuList_ID



SELECT * FROM SCMENU 
INNER JOIN SCMENU_SCSUBMENU
ON SCMENU.ID = SCMENU_SCSUBMENU.scmenuList_ID
INNER JOIN SCSUBMENU
ON SCSUBMENU.ID = SCMENU_SCSUBMENU.scsubmenuList_ID

SELECT column_name(s)
FROM table1
INNER JOIN table2
ON table1.column_name = table2.column_name;




SELECT * FROM SCMENU 
INNER JOIN SCMENU_SCSUBMENU
ON SCMENU.ID = SCMENU_SCSUBMENU.scmenuList_ID
INNER JOIN SCSUBMENU
ON SCSUBMENU.ID = SCMENU_SCSUBMENU.scsubmenuList_ID
WHERE SCMENU.ID = SCMENU



SELECT * FROM SCSUBMENU 
INNER JOIN SCMENU_SCSUBMENU
ON SCSUBMENU.ID = SCMENU_SCSUBMENU.scsubmenuList_ID
WHERE SCMENU_SCSUBMENU.scmenuList_ID = 2452










