SELECT * FROM PRODUCTOCATEGORIA




SELECT * FROM PRODUCTOCATEGORIA
INNER JOIN SCSUBMENU_PRODUCTOCATEGORIA
ON PRODUCTOCATEGORIA.ID = SCSUBMENU_PRODUCTOCATEGORIA.productocategoriaList_ID AND SCSUBMENU_PRODUCTOCATEGORIA.scsubmenuList_ID = 2656;



INSERT INTO cms360.dbo.PRODUCTOTIPOLIKE (ID,DIRECCIONTXT1,DIRECCIONTXT2,DIRECCIONTXT3,EQUIPESOS,FECHA_CREACION,FECHA_FIN,IMAGEN,LIKES,NOMBRE,PORCENTAJEINFO,PRECIO,SUBTITULO,TITULO,TITULO_DETALLES,TUTULO_DIRECCIONES) VALUES 
(13,NULL,NULL,NULL,NULL,NULL,NULL,'/resource/images/olive-oil-salad-dressing-cooking-olive.jpg',NULL,NULL,NULL,7500,'7500','Aderezo Machitún3xcxcxcx',NULL,NULL)
;

